name: FNAFNetLocal-width32
class_name: basicsr.models.archs.FNAFNet_arch.FNAFNetLocal
params:
  width: 32
  enc_blk_nums: [1, 1, 1, 28]
  middle_blk_num: 1
  dec_blk_nums: [1, 1, 1, 1]
  window_size_e: [64,32,16,8]
  window_size_e_fft: [64,32,16,-1]
