name: SoftANAFNetLocal-width32
class_name: basicsr.models.archs.NAFNet_with_soft_attention_arch.SoftANAFNetLocal
params:
  width: 32
  enc_blk_nums: [1, 1, 1, 28]
  middle_blk_num: 1
  dec_blk_nums: [1, 1, 1, 1]
